name: scDock
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _r-mutex=1.0.1=anacondar_1
  - attr=2.5.2=h39aace5_0
  - binutils_impl_linux-64=2.44=h4bf12b8_1
  - brotli-python=1.0.9=py310h6a678d5_9
  - bwidget=1.10.1=ha770c72_1
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.1.31=hbcca054_0
  - cairo=1.18.4=h3394656_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - curl=8.14.1=h332b0f4_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=h1110e0f_3
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.13.3=ha770c72_1
  - fribidi=1.0.10=h36c2ea0_0
  - gcc_impl_linux-64=13.2.0=h9eb54c0_7
  - gfortran_impl_linux-64=13.2.0=h9efe08d_13
  - glpk=5.0=h445213a_0
  - gmp=6.3.0=hac33072_2
  - graphite2=1.3.14=hecca717_2
  - gsl=2.7=he838d99_0
  - gxx_impl_linux-64=13.2.0=h2a599c4_7
  - harfbuzz=11.4.5=h15599e2_0
  - hdf5=1.14.6=mpi_mvapich_h15d2f67_3
  - icu=75.1=he02047a_0
  - kernel-headers_linux-64=3.10.0=he073ed8_18
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.21.3=h659f571_0
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.44=h1423503_1
  - lerc=4.0.0=h0aef613_1
  - libaec=1.1.4=h3f801dc_0
  - libblas=3.9.0=35_h59b9bed_openblas
  - libboost=1.86.0=hed09d94_4
  - libboost-python=1.86.0=py310hc563356_4
  - libcap=2.75=h39aace5_0
  - libcblas=3.9.0=35_he106b2a_openblas
  - libcurl=8.14.1=h332b0f4_0
  - libdeflate=1.24=h86f0d12_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libevent=2.1.12=hdbd6064_1
  - libexpat=2.7.1=hecca717_0
  - libfabric=2.2.0=ha770c72_2
  - libfabric1=2.2.0=h3ff6011_2
  - libffi=3.4.6=h2dba641_1
  - libfreetype=2.13.3=ha770c72_1
  - libfreetype6=2.13.3=h48d6fc4_1
  - libgcc=15.1.0=h767d61c_5
  - libgcc-devel_linux-64=13.2.0=hceb6213_107
  - libgcc-ng=15.1.0=h69a702a_5
  - libgcrypt-lib=1.11.1=hb9d3cd8_0
  - libgfortran=15.1.0=h69a702a_5
  - libgfortran-ng=15.1.0=h69a702a_5
  - libgfortran5=15.1.0=hcea5267_5
  - libgit2=1.9.1=h014eb84_0
  - libglib=2.84.3=hf39c6af_0
  - libgomp=15.1.0=h767d61c_5
  - libgpg-error=1.55=h3f2d84a_0
  - libhwloc=2.11.2=default_h3d81e11_1002
  - libiconv=1.18=h3b78370_2
  - libjpeg-turbo=3.1.0=hb9d3cd8_0
  - libkrb5=1.21.3=h520c7b4_4
  - liblapack=3.9.0=35_h7ac8fdf_openblas
  - liblzma=5.8.1=hb9d3cd8_2
  - libnghttp2=1.67.0=had1ee68_0
  - libnl=3.11.0=hb9d3cd8_0
  - libnsl=2.0.1=hb9d3cd8_1
  - libopenblas=0.3.30=pthreads_h94d23a6_2
  - libpng=1.6.50=h421ea60_1
  - libpq=17.6=h3675c94_1
  - librdkit=2025.03.6=h3c5c181_0
  - libsanitizer=13.2.0=h6ddb7a1_7
  - libsodium=1.0.18=h7b6447c_0
  - libsqlite=3.50.4=h0c1763c_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.1.0=h8f9b012_5
  - libstdcxx-devel_linux-64=13.2.0=hceb6213_107
  - libstdcxx-ng=15.1.0=h4852527_5
  - libsystemd0=257.7=h4e0b6ca_0
  - libtiff=4.7.0=h8261f1e_6
  - libudev1=257.7=hbe16f8c_0
  - libuuid=2.38.1=h0b41bf4_0
  - libuv=1.51.0=hb03c661_1
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.13.8=h04c0eec_1
  - libzlib=1.3.1=hb9d3cd8_2
  - lmdb=0.9.31=hb25bd0a_0
  - lz4-c=1.10.0=h5888daf_1
  - make=4.4.1=hb9d3cd8_2
  - matplotlib-base=3.10.5=py310h9489213_0
  - mpi=1.0.1=mvapich
  - mvapich=4.0=hd71cc9b_4
  - ncurses=6.5=h2d0b736_3
  - nlopt=2.9.0=py310ha22d986_0
  - openjpeg=2.5.2=h0d4d230_1
  - openldap=2.6.10=h8e75217_0
  - openssl=3.5.2=h26f9b46_0
  - pandoc=3.7.0.2=ha770c72_0
  - pango=1.56.3=h9ac818e_1
  - pcre2=10.45=hc749103_0
  - pip=25.2=pyh8b19718_0
  - pixman=0.46.4=h54a6638_1
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pycparser=2.21=pyhd3eb1b0_0
  - python=3.10.18=hd6af730_0_cpython
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python_abi=3.10=6_cp310
  - r-askpass=1.2.1=r44h2b5f3a1_0
  - r-assertthat=0.2.1=r44hc72bb7e_5
  - r-base=4.4.3=h85845a0_2
  - r-base64enc=0.1_3=r44hb1dbf0f_1007
  - r-bit=4.6.0=r44h2b5f3a1_0
  - r-bit64=4.6.0_1=r44h2b5f3a1_0
  - r-brew=1.0_10=r44hc72bb7e_1
  - r-brio=1.1.5=r44hb1dbf0f_1
  - r-bslib=0.9.0=r44hc72bb7e_0
  - r-cachem=1.1.0=r44hb1dbf0f_1
  - r-callr=3.7.6=r44hc72bb7e_1
  - r-cli=3.6.5=r44h93ab643_0
  - r-clipr=0.8.0=r44hc72bb7e_3
  - r-colorspace=2.1_1=r44hdb488b9_0
  - r-commonmark=2.0.0=r44h2b5f3a1_0
  - r-cpp11=0.5.2=r44h785f33e_1
  - r-crayon=1.5.3=r44hc72bb7e_1
  - r-credentials=2.0.2=r44hc72bb7e_0
  - r-curl=7.0.0=r44h10955f1_0
  - r-desc=1.4.3=r44hc72bb7e_1
  - r-devtools=2.4.5=r44hc72bb7e_3
  - r-diffobj=0.3.6=r44h2b5f3a1_0
  - r-digest=0.6.37=r44h0d4f4ea_0
  - r-downlit=0.4.4=r44hc72bb7e_1
  - r-ellipsis=0.3.2=r44hb1dbf0f_3
  - r-evaluate=1.0.5=r44hc72bb7e_0
  - r-fansi=1.0.6=r44hb1dbf0f_1
  - r-farver=2.1.2=r44ha18555a_1
  - r-fastmap=1.2.0=r44ha18555a_1
  - r-fontawesome=0.5.3=r44hc72bb7e_0
  - r-fs=1.6.6=r44h93ab643_0
  - r-gert=2.1.5=r44h5e22a44_0
  - r-ggplot2=3.5.2=r44hc72bb7e_0
  - r-gh=1.5.0=r44hc72bb7e_0
  - r-gitcreds=0.1.2=r44hc72bb7e_3
  - r-glue=1.8.0=r44h2b5f3a1_0
  - r-gtable=0.3.6=r44hc72bb7e_0
  - r-hdf5r=1.3.12=r44ha6b0525_1
  - r-highr=0.11=r44hc72bb7e_1
  - r-htmltools=0.5.8.1=r44ha18555a_1
  - r-htmlwidgets=1.6.4=r44h785f33e_3
  - r-httpuv=1.6.16=r44h6d565e7_0
  - r-httr=1.4.7=r44hc72bb7e_1
  - r-httr2=1.2.1=r44hc72bb7e_0
  - r-igraph=2.1.4=r44hadbbdbc_0
  - r-ini=0.3.1=r44hc72bb7e_1006
  - r-isoband=0.2.7=r44ha18555a_3
  - r-jquerylib=0.1.4=r44hc72bb7e_3
  - r-jsonlite=2.0.0=r44h2b5f3a1_0
  - r-knitr=1.50=r44hc72bb7e_0
  - r-labeling=0.4.3=r44hc72bb7e_1
  - r-later=1.4.4=r44h3697838_0
  - r-lattice=0.22_7=r44h2b5f3a1_0
  - r-leidenbase=0.1.32=r44he61314c_0
  - r-lifecycle=1.0.4=r44hc72bb7e_1
  - r-magrittr=2.0.3=r44hb1dbf0f_3
  - r-mass=7.3_64=r44h2b5f3a1_0
  - r-matrix=1.7_4=r44h0e4624f_0
  - r-memoise=2.0.1=r44hc72bb7e_3
  - r-mgcv=1.9_3=r44h2ae2be5_0
  - r-mime=0.13=r44h2b5f3a1_0
  - r-miniui=0.1.2=r44hc72bb7e_0
  - r-munsell=0.5.1=r44hc72bb7e_1
  - r-nlme=3.1_168=r44hb67ce94_0
  - r-nloptr=2.2.1=r44hb8c4c88_0
  - r-openssl=2.3.3=r44he8289e2_0
  - r-pillar=1.11.0=r44hc72bb7e_0
  - r-pkgbuild=1.4.8=r44hc72bb7e_0
  - r-pkgconfig=2.0.3=r44hc72bb7e_4
  - r-pkgdown=2.1.3=r44hc72bb7e_0
  - r-pkgload=1.4.0=r44hc72bb7e_0
  - r-praise=1.0.0=r44hc72bb7e_1008
  - r-prettyunits=1.2.0=r44hc72bb7e_1
  - r-processx=3.8.6=r44h2b5f3a1_0
  - r-profvis=0.4.0=r44h2b5f3a1_0
  - r-promises=1.3.3=r44h3697838_0
  - r-ps=1.9.1=r44h2b5f3a1_0
  - r-purrr=1.1.0=r44h54b55ab_0
  - r-r6=2.6.1=r44hc72bb7e_0
  - r-ragg=1.5.0=r44h9f1dc4d_0
  - r-rappdirs=0.3.3=r44hb1dbf0f_3
  - r-rcmdcheck=1.4.0=r44h785f33e_3
  - r-rcolorbrewer=1.1_3=r44h785f33e_3
  - r-rcpp=1.1.0=r44h93ab643_0
  - r-rematch2=2.1.2=r44hc72bb7e_4
  - r-remotes=2.5.0=r44hc72bb7e_1
  - r-rlang=1.1.6=r44h93ab643_0
  - r-rmarkdown=2.29=r44hc72bb7e_0
  - r-roxygen2=7.3.3=r44h3697838_0
  - r-rprojroot=2.1.1=r44hc72bb7e_0
  - r-rstudioapi=0.17.1=r44hc72bb7e_0
  - r-rversions=2.1.2=r44hc72bb7e_3
  - r-sass=0.4.10=r44h93ab643_0
  - r-scales=1.4.0=r44hc72bb7e_0
  - r-sessioninfo=1.2.3=r44hc72bb7e_0
  - r-shiny=1.11.1=r44h785f33e_0
  - r-sourcetools=0.1.7_1=r44ha18555a_2
  - r-stringi=1.8.7=r44h3c328a7_0
  - r-stringr=1.5.1=r44h785f33e_1
  - r-sys=3.4.3=r44h2b5f3a1_0
  - r-systemfonts=1.2.3=r44h74f4acd_0
  - r-testthat=3.2.3=r44h3697838_1
  - r-textshaping=1.0.3=r44h74f4acd_0
  - r-tibble=3.3.0=r44h2b5f3a1_0
  - r-tinytex=0.57=r44hc72bb7e_0
  - r-urlchecker=1.0.1=r44hc72bb7e_3
  - r-usethis=3.2.1=r44hc72bb7e_0
  - r-utf8=1.2.6=r44h2b5f3a1_0
  - r-vctrs=0.6.5=r44h0d4f4ea_1
  - r-viridislite=0.4.2=r44hc72bb7e_2
  - r-waldo=0.6.2=r44hc72bb7e_0
  - r-whisker=0.4.1=r44hc72bb7e_2
  - r-withr=3.0.2=r44hc72bb7e_0
  - r-xfun=0.53=r44h3697838_0
  - r-xml2=1.4.0=r44hc6fd541_0
  - r-xopen=1.0.1=r44hc72bb7e_1
  - r-xtable=1.8_4=r44hc72bb7e_6
  - r-yaml=2.3.10=r44hdb488b9_0
  - r-zip=2.3.3=r44h2b5f3a1_0
  - rdma-core=59.0=hecca717_0
  - readline=8.2=h8c095d6_2
  - sed=4.9=h6688a6e_0
  - setuptools=80.9.0=pyhff2d567_0
  - sysroot_linux-64=2.17=h0157908_18
  - tk=8.6.13=noxft_hd72426e_102
  - tktable=2.10=h8d826fa_7
  - typing_extensions=4.15.0=py310h06a4308_0
  - tzdata=2025b=h78e105d_0
  - ucx=1.19.0=hc93acc0_3
  - wheel=0.45.1=pyhd8ed1ab_1
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxt=1.3.1=hb9d3cd8_0
  - zlib=1.3.1=hb9d3cd8_2
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
    - autodocktools-py3==1.5.7.post1+12.ga62a5d9
    - brotli==1.0.9
    - brotlicffi==1.0.9.2
    - certifi==2025.8.3
    - cffi==1.17.1
    - contourpy==1.3.1
    - fonttools==4.55.3
    - greenlet==3.1.1
    - idna==3.7
    - joblib==1.5.2
    - kiwisolver==1.4.8
    - llvmlite==0.44.0
    - matplotlib==3.10.5
    - numba==0.61.2
    - numpy==2.2.6
    - packaging==25.0
    - pandas==2.3.2
    - pillow==10.4.0
    - pycairo==1.23.0
    - pynndescent==0.5.13
    - pyparsing==3.2.0
    - pysocks==1.7.1
    - python-dateutil==2.9.0.post0
    - pytz==2025.2
    - rdkit==2025.3.6
    - reportlab==4.4.3
    - requests==2.32.5
    - scikit-learn==1.7.1
    - scipy==1.15.3
    - six==1.17.0
    - sqlalchemy==2.0.43
    - threadpoolctl==3.6.0
    - tqdm==4.67.1
    - typing-extensions==4.15.0
    - umap-learn==0.5.9.post2
    - unicodedata2==15.1.0
    - urllib3==2.5.0
prefix: /home/andrew/anaconda3/envs/scDock

