name: scDock
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _r-mutex=1.0.1
  - attr=2.5.2
  - binutils_impl_linux-64=2.44
  - brotli-python=1.0.9
  - bwidget=1.10.1
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.1.31
  - cairo=1.18.4
  - charset-normalizer=3.3.2
  - curl=8.14.1
  - cycler=0.11.0
  - cyrus-sasl=2.1.28
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.13.3
  - fribidi=1.0.10
  - gcc_impl_linux-64=13.2.0
  - gfortran_impl_linux-64=13.2.0
  - glpk=5.0
  - gmp=6.3.0
  - graphite2=1.3.14
  - gsl=2.7
  - gxx_impl_linux-64=13.2.0
  - harfbuzz=11.4.5
  - hdf5=1.14.6
  - icu=75.1
  - kernel-headers_linux-64=3.10.0
  - keyutils=1.6.3
  - krb5=1.21.3
  - lcms2=2.17
  - ld_impl_linux-64=2.44
  - lerc=4.0.0
  - libaec=1.1.4
  - libblas=3.9.0
  - libboost=1.86.0
  - libboost-python=1.86.0
  - libcap=2.75
  - libcblas=3.9.0
  - libcurl=8.14.1
  - libdeflate=1.24
  - libedit=3.1.20250104
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.7.1
  - libfabric=2.2.0
  - libfabric1=2.2.0
  - libffi=3.4.6
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgcc=15.1.0
  - libgcc-devel_linux-64=13.2.0
  - libgcc-ng=15.1.0
  - libgcrypt-lib=1.11.1
  - libgfortran=15.1.0
  - libgfortran-ng=15.1.0
  - libgfortran5=15.1.0
  - libgit2=1.9.1
  - libglib=2.84.3
  - libgomp=15.1.0
  - libgpg-error=1.55
  - libhwloc=2.11.2
  - libiconv=1.18
  - libjpeg-turbo=3.1.0
  - libkrb5=1.21.3
  - liblapack=3.9.0
  - liblzma=5.8.1
  - libnghttp2=1.67.0
  - libnl=3.11.0
  - libnsl=2.0.1
  - libopenblas=0.3.30
  - libpng=1.6.50
  - libpq=17.6
  - librdkit=2025.03.6
  - libsanitizer=13.2.0
  - libsodium=1.0.18
  - libsqlite=3.50.4
  - libssh2=1.11.1
  - libstdcxx=15.1.0
  - libstdcxx-devel_linux-64=13.2.0
  - libstdcxx-ng=15.1.0
  - libsystemd0=257.7
  - libtiff=4.7.0
  - libudev1=257.7
  - libuuid=2.38.1
  - libuv=1.51.0
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxml2=2.13.8
  - libzlib=1.3.1
  - lmdb=0.9.31
  - lz4-c=1.10.0
  - make=4.4.1
  - matplotlib-base=3.10.5
  - mpi=1.0.1
  - mvapich=4.0
  - ncurses=6.5
  - nlopt=2.9.0
  - openjpeg=2.5.2
  - openldap=2.6.10
  - openssl=3.5.2
  - pandoc=3.7.0.2
  - pango=1.56.3
  - pcre2=10.45
  - pip=25.2
  - pixman=0.46.4
  - pthread-stubs=0.4
  - pycparser=2.21
  - python=3.10.18
  - python-tzdata=2025.2
  - python_abi=3.10
  - r-askpass=1.2.1
  - r-assertthat=0.2.1
  - r-base=4.4.3
  - r-base64enc=0.1_3
  - r-bit=4.6.0
  - r-bit64=4.6.0_1
  - r-brew=1.0_10
  - r-brio=1.1.5
  - r-bslib=0.9.0
  - r-cachem=1.1.0
  - r-callr=3.7.6
  - r-cli=3.6.5
  - r-clipr=0.8.0
  - r-colorspace=2.1_1
  - r-commonmark=2.0.0
  - r-cpp11=0.5.2
  - r-crayon=1.5.3
  - r-credentials=2.0.2
  - r-curl=7.0.0
  - r-desc=1.4.3
  - r-devtools=2.4.5
  - r-diffobj=0.3.6
  - r-digest=0.6.37
  - r-downlit=0.4.4
  - r-ellipsis=0.3.2
  - r-evaluate=1.0.5
  - r-fansi=1.0.6
  - r-farver=2.1.2
  - r-fastmap=1.2.0
  - r-fontawesome=0.5.3
  - r-fs=1.6.6
  - r-gert=2.1.5
  - r-ggplot2=3.5.2
  - r-gh=1.5.0
  - r-gitcreds=0.1.2
  - r-glue=1.8.0
  - r-gtable=0.3.6
  - r-hdf5r=1.3.12
  - r-highr=0.11
  - r-htmltools=0.5.8.1
  - r-htmlwidgets=1.6.4
  - r-httpuv=1.6.16
  - r-httr=1.4.7
  - r-httr2=1.2.1
  - r-igraph=2.1.4
  - r-ini=0.3.1
  - r-isoband=0.2.7
  - r-jquerylib=0.1.4
  - r-jsonlite=2.0.0
  - r-knitr=1.50
  - r-labeling=0.4.3
  - r-later=1.4.4
  - r-lattice=0.22_7
  - r-leidenbase=0.1.32
  - r-lifecycle=1.0.4
  - r-magrittr=2.0.3
  - r-mass=7.3_64
  - r-matrix=1.7_4
  - r-memoise=2.0.1
  - r-mgcv=1.9_3
  - r-mime=0.13
  - r-miniui=0.1.2
  - r-munsell=0.5.1
  - r-nlme=3.1_168
  - r-nloptr=2.2.1
  - r-openssl=2.3.3
  - r-pillar=1.11.0
  - r-pkgbuild=1.4.8
  - r-pkgconfig=2.0.3
  - r-pkgdown=2.1.3
  - r-pkgload=1.4.0
  - r-praise=1.0.0
  - r-prettyunits=1.2.0
  - r-processx=3.8.6
  - r-profvis=0.4.0
  - r-promises=1.3.3
  - r-ps=1.9.1
  - r-purrr=1.1.0
  - r-r6=2.6.1
  - r-ragg=1.5.0
  - r-rappdirs=0.3.3
  - r-rcmdcheck=1.4.0
  - r-rcolorbrewer=1.1_3
  - r-rcpp=1.1.0
  - r-rematch2=2.1.2
  - r-remotes=2.5.0
  - r-rlang=1.1.6
  - r-rmarkdown=2.29
  - r-roxygen2=7.3.3
  - r-rprojroot=2.1.1
  - r-rstudioapi=0.17.1
  - r-rversions=2.1.2
  - r-sass=0.4.10
  - r-scales=1.4.0
  - r-sessioninfo=1.2.3
  - r-shiny=1.11.1
  - r-sourcetools=0.1.7_1
  - r-stringi=1.8.7
  - r-stringr=1.5.1
  - r-sys=3.4.3
  - r-systemfonts=1.2.3
  - r-testthat=3.2.3
  - r-textshaping=1.0.3
  - r-tibble=3.3.0
  - r-tinytex=0.57
  - r-urlchecker=1.0.1
  - r-usethis=3.2.1
  - r-utf8=1.2.6
  - r-vctrs=0.6.5
  - r-viridislite=0.4.2
  - r-waldo=0.6.2
  - r-whisker=0.4.1
  - r-withr=3.0.2
  - r-xfun=0.53
  - r-xml2=1.4.0
  - r-xopen=1.0.1
  - r-xtable=1.8_4
  - r-yaml=2.3.10
  - r-zip=2.3.3
  - rdma-core=59.0
  - readline=8.2
  - sed=4.9
  - setuptools=80.9.0
  - sysroot_linux-64=2.17
  - tk=8.6.13
  - tktable=2.10
  - typing_extensions=4.15.0
  - tzdata=2025b
  - ucx=1.19.0
  - wheel=0.45.1
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxrender=0.9.12
  - xorg-libxt=1.3.1
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
    - autodocktools-py3==1.5.7.post1+12.ga62a5d9
    - brotli==1.0.9
    - brotlicffi==1.0.9.2
    - certifi==2025.8.3
    - cffi==1.17.1
    - contourpy==1.3.1
    - fonttools==4.55.3
    - greenlet==3.1.1
    - idna==3.7
    - joblib==1.5.2
    - kiwisolver==1.4.8
    - llvmlite==0.44.0
    - matplotlib==3.10.5
    - numba==0.61.2
    - numpy==2.2.6
    - packaging==25.0
    - pandas==2.3.2
    - pillow==10.4.0
    - pycairo==1.23.0
    - pynndescent==0.5.13
    - pyparsing==3.2.0
    - pysocks==1.7.1
    - python-dateutil==2.9.0.post0
    - pytz==2025.2
    - rdkit==2025.3.6
    - reportlab==4.4.3
    - requests==2.32.5
    - scikit-learn==1.7.1
    - scipy==1.15.3
    - six==1.17.0
    - sqlalchemy==2.0.43
    - threadpoolctl==3.6.0
    - tqdm==4.67.1
    - typing-extensions==4.15.0
    - umap-learn==0.5.9.post2
    - unicodedata2==15.1.0
    - urllib3==2.5.0
prefix: /home/andrew/anaconda3/envs/scDock

